#ifndef PIXELFORGE_VALIDATION_HELPERS_HELPERS_HPP
#define PIXELFORGE_VALIDATION_HELPERS_HELPERS_HPP

#define REQUIRE_PF_REQUIRE_FAIL(val) \
  REQUIRE_THROWS_AS(val, RequireFail);

#endif /* PIXELFORGE_VALIDATION_HELPERS_HELPERS_HPP */
