set(PIXELFORGE_REQUIRE_FAIL_LOG_BUF_SIZE 64 CACHE STRING
  "Define the size of the logging buffer used when requireFail policy is set to log and continue"
)

option(PIXELFORGE_ENABLE_FAST_LOG_BACKEND "Enable the fast logger backend" ON)

set(PIXELFORGE_FAST_LOG_BACKEND_BLOCK_SIZE 1024 CACHE STRING
  "The block size of fast logger backend"
)
set(PIXELFORGE_FAST_LOG_BACKEND_COLLECTOR_BLOCK_COUNT 1024 CACHE STRING
  "The block size of fast logger backend"
)

target_compile_definitions(PixelForge_core PUBLIC
  PIXELFORGE_REQUIRE_FAIL_LOG_BUF_SIZE=${PIXELFORGE_REQUIRE_FAIL_LOG_BUF_SIZE}
)

if(PIXELFORGE_ENABLE_FAST_LOG_BACKEND) 
  target_compile_definitions(PixelForge_logging PUBLIC 
    PIXELFORGE_ENABLE_FAST_LOG_BACKEND
    PIXELFORGE_FAST_LOG_BACKEND_COLLECTOR_BLOCK_COUNT=${PIXELFORGE_FAST_LOG_BACKEND_COLLECTOR_BLOCK_COUNT}
    PIXELFORGE_FAST_LOG_BACKEND_BLOCK_SIZE=${PIXELFORGE_FAST_LOG_BACKEND_BLOCK_SIZE}
  )
endif()
